[package]
name = "quirkmm_simulator"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
ndarray = "0.17.2"
num-complex = "0.4.6"
wasm-bindgen = "0.2.115"
ts-rs = "12.0.1"
serde = { version = "1.0.228", features = ["derive"] }
serde-wasm-bindgen = "0.6.5"
console_log = { version = "1.0.0" }
log = "0.4.29"
