// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SingleQbitGate } from "./SingleQbitGate";

export type Gate = { "SingleQbit": [SingleQbitGate, number] } | { "CNot": [number, number] };
