// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComplexValue } from "./ComplexValue";

export type QubitInfo = { index: number, reduced_density: Array<Array<ComplexValue>>, purity: number, is_separable: boolean, bloch_vector: [number, number, number], };
