// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StateSnapshot } from "./StateSnapshot";

export type SimulationStage = { step: number, description: string, clean: StateSnapshot, dirty: StateSnapshot, fidelity: number, };
