// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Gate } from "./Gate";

export type Circuit = { n_qbits: number, gates: Array<Gate>, };
