// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NoiseModel = { t1: number, t2: number, p_depolarize: number, gate_time: number, };
