// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComplexValue } from "./ComplexValue";
import type { QubitInfo } from "./QubitInfo";

export type StateSnapshot = { density_matrix: Array<Array<ComplexValue>>, state_vector: Array<ComplexValue> | null, qubits: Array<QubitInfo>, };
